FROM node:20

WORKDIR /app

COPY pakage*.json .

COPY . .

RUN npm install

RUN npx nx run formBuilder:build

ENV PORT=4000

EXPOSE 4000

CMD [ "npx" , "nx" , "run", "formBuilder:start", "--port", "4000" ]